version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
build_script:
- cmd: >-
    dotnet publish --configuration Release

    ./AppVeyor.bat
artifacts:
- path: SyncClipboard/bin/Release/net6.0-windows10.0.17763.0/win-x64/publish/SyncClipboard.exe
  name: SyncClipboard_$(VERSION)
# deploy:
# - provider: GitHub
#   release: $(VERSION)
#   description: $(FEATURE)
#   auth_token:
#     secure: zuPhf3Nx5b5FX/XCtz5/goxwD1t3htaC59DgWs2AiaeNdoTssqKoT1QX+2S+h3pr
#   artifact: SyncClipboard_$(VERSION)
#   force_update: true
#   on:
#     APPVEYOR_REPO_TAG: true