version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
after_build:
- cmd: AppVeyor.bat
artifacts:
- path: SyncClipboard\bin\Release\SyncClipboard.exe
  name: SyncClipboard_$(VERSION)
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(FEATURE)
  auth_token:
    secure: yWzcVxxzOxtNtkULlYk7YhliLYB3TNM5upWKfzmoLBHPY+hoypQr6/XHBEWB3chq
  artifact: SyncClipboard_$(VERSION)
  force_update: false
  on:
    APPVEYOR_REPO_TAG: true