name: build

permissions:
    contents: write
on:
  push:
    branches:
      - '**'
    tags: 
      - 'v*'
  pull_request:

jobs:
  winui:
    uses: ./.github/workflows/winui-package.yml

  deskop:
    uses: ./.github/workflows/desktop-package.yml
    with:
        checkout-repo: ${{ github.repository }}
        checkout-ref: ${{ github.ref }}