name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Check code style
      run: dotnet format --verify-no-changes

    - name: Build
      run: dotnet publish --configuration Release --no-restore

    - name: Generate change log
      run: |
        .\PreRelease.bat
        type feature.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SyncClipboard
        path: SyncClipboard/bin/Release/net6.0-windows10.0.17763.0/win-x64/publish/SyncClipboard.exe
    
    - name: Upload change log
      uses: actions/upload-artifact@v3
      with:
        name: feature
        path:
          feature.txt