name: build-progress

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Install dependencies
      run: dotnet restore

    - name: Check code style
      run: dotnet format --verify-no-changes --no-restore

    - name: Check code style info
      run: |
        dotnet format --severity info --verify-no-changes --no-restore
        exit 0

    - name: Build Winform
      run: dotnet publish SyncClipboard\SyncClipboard.csproj -c Release -r win-x64 --no-self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

    - name: Generate change log
      run: |
        .\PreRelease.bat
        type feature.txt

    - name: Upload build artifacts RemoteCommand
      uses: actions/upload-artifact@v3
      with:
        name: RemoteCommand
        path: SyncClipboard/bin/Release/net6.0-windows10.0.17763.0/win-x64/publish/RemoteCommand.exe

    - name: Upload change log
      uses: actions/upload-artifact@v3
      with:
        name: feature
        path: feature.txt