name: entry

on:
  push:
    branches:
      - '**'
    tags: 
      - 'v*'
  pull_request:

jobs:
  winui:
    uses: ./.github/workflows/winui-package.yml

  deskop:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }} 
    uses: ./.github/workflows/desktop-package.yml