name: release

permissions:
  contents: write

on:
  push:
    branches: 
      - master
    tags: 
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download last-job-built artifact
        uses: actions/download-artifact@v3
        with:
          name: SyncClipboard

      - name: Download last-job-built change log
        uses: actions/download-artifact@v3
        with:
          name: feature

      - name: Show change log
        run: |
          tree /f
          type feature.txt

      - name: Publish Github Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: feature.txt
          files: SyncClipboard.exe